Работа с БД из PHP
htmlacademy-php/265853-readme-12 pull request #9
Opened 2020-06-11 14:46 UTC by EgorTolbaev

2020-06-16 13:00 UTC, VikingBO requested changes
Мне нравится что ты стараешься доработать код и сделать его более удобным в использовании, осталось поправить некоторые моменты и будет прекрасно :)

2020-06-16 13:00 UTC, VikingBO commented on connection.php
> +<?php
супер что ты вынес в отдельный файл данные для подключения, но почему ты не вынес и само подключение я не совсем понял, почему ты процесс подключения оставляешь в index.php ?

2020-06-16 13:00 UTC, VikingBO commented on index.php
> +    $final_result[] = null;
оуоуоу, ты добавляешь первый элемент массива null для начала не задав саму переменную, не указав что она в принципе массив да еще и в последующем ты переписываешь саму переменную.... в чем логика?

2020-06-16 13:00 UTC, VikingBO commented on index.php
> +            $final_result = mysqli_fetch_all($result, MYSQLI_ASSOC);
Ты же понимаешь что значение переменной будет переписываться каждый раз когда ты будешь получать результат и в конечном счете ты вернешь только последнюю строку ответа?
Если не заметил то повнимательней.

2020-06-16 13:00 UTC, VikingBO commented on index.php
> +        if ($result = mysqli_store_result($connect)) {
вот тут я не совсем согласен, да так можно но всё же лучше выносить присваивание за пределы проверки, так будет лучше читаемость и понимание кода. Лучше сразу привыкать, что бы потом не писать излишне коротких проверок.

2020-06-16 13:00 UTC, VikingBO commented on index.php
> +function requestHandler(mysqli $connect, string $stringSQL): array
я думаю вообще подобные методы лучше все вынести в отдельный файл, как и подключение к БД соответственно.

2020-06-16 13:00 UTC, VikingBO commented on templates/main.php
> +                зачем это надо:)-->
Здесь всё верно, ты молодец что подметил подобное, да это действительно можно сделать простым перебором так как типы ты передаешь извне параметром, а не прописываешь руками и есть возможность просто одинаковые блоки делать бесконечно много с изменением пары параметров. Правда не вижу смысла оборачивать в скобки, это излишняя информация, достаточно просто указать выводимый параметр

2020-06-17 10:02 UTC, EgorTolbaev commented on connection.php
> +<?php
Я хотел это вынести,но не вынес потому что у нас все функции  в index.php.
Вообще, я думал все вынести или в отдельный сценарий например function.php и отдельно для работы с базой, или еще сильней все разделить типа отдельно работа с текстом(там все функции для строк), отдельно база и т.д , а в index.php оставить только вызов этих функций.
что думаешь по этому поводу ?

2020-06-17 10:18 UTC, VikingBO commented on connection.php
> +<?php
да, было бы надежнее вынести в отдельные файлы сгруппировав по назначению, для работы с БД в один, для работы со строками в другой ну и т.д.

2020-06-17 10:24 UTC, EgorTolbaev commented on index.php
> +            $final_result = mysqli_fetch_all($result, MYSQLI_ASSOC);
Да, тут вообще этот while, это я смотрел документацию и там выводили сразу при каждой итерации все через html и когда переписывал под себя не обратил внимания на этот момент.

2020-06-17 10:30 UTC, EgorTolbaev commented on index.php
> +    $final_result[] = null;
Тут логика в том что, я так решил обявить этот массив и имел ввиду что массив пустой(теперь понял что это не правильно, а я просто сказал что первый элемент null).
Наверное нужно так: $final_result = array();

2020-06-17 10:53 UTC, VikingBO commented on index.php
> +    $final_result[] = null;
Можно и так, можно и короткой записью
`$final_result = [];`
если тебе нужно задать какое-либо значение то ты можешь сразу это указать
`$final_result = ['text',null,1];`

2020-06-20 05:46 UTC, VikingBO requested changes
В целом круто что ты решил еще и в классах разобраться, но почему тогда connection у тебя представлен просто как файл с методами.

2020-06-20 05:46 UTC, VikingBO commented on templates/main.php
> +                        <p><?= $StringHelper ->cropText($post_content) ?></p>
Пробел лишний после $StringHelper, да и первый символ переменной по стандартам не должен быть в верхнем регистре.

2020-06-20 15:46 UTC, VikingBO approved these changes
Давай так, мне всё нравится кроме одного момента с константами, в целом это не ошибка, я реквест принимаю но на заметку возьмем и обсудим, потому как этот момент может выстрелить в будущем.

2020-06-20 15:46 UTC, merged